/************************************************************************
*                             Os Services                               *
*************************************************************************
* FileName:         syst_ser.c                                          *
* HW:               Mercury System                                      *
* Author:           F.Ficili                                            *
*                                                                       *
* Software License Agreement:                                           *
*                                                                       *
* THIS SOFTWARE IS PROVIDED IN AN "AS IS" CONDITION. NO WARRANTIES,     *
* WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT NOT LIMITED     *
* TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A           *
* PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. THE AUTHOR SHALL NOT,      *
* IN ANY CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL OR            *
* CONSEQUENTIAL DAMAGES, FOR ANY REASON WHATSOEVER.                     *
*                                                                       *  
* --------------------------------------------------------------------- * 
* Responsible For This File: Francesco Ficili                           *
*                                                                       *
* --------------------------------------------------------------------- *
* Author       Date        Version      Comment                         *
* ---------------------------------------------------------------------	*
* F.Ficili     24/07/16    1.0          First release                   *
************************************************************************/

/************************************************************************
* Includes
************************************************************************/
#include "os_ser.h"

/************************************************************************
* Defines
************************************************************************/


/************************************************************************
* Typedefs
************************************************************************/


/************************************************************************
* LOCAL Variables
************************************************************************/


/************************************************************************
* GLOBAL Variables
************************************************************************/


/************************************************************************
* LOCAL Function Prototypes
************************************************************************/


/************************************************************************
* LOCAL Function Implementations
************************************************************************/


/************************************************************************
* GLOBAL Function Implementations
************************************************************************/

/************************************************************************
* Function:     void GenerateEvt (EventStructureType *Event)
* Input:        EventStructureType *Event
* Output:       EventStatusType
* Author:       F.Ficili	
* Description:  API to generate an event. 
*               The API takes an event variable passed by reference as an input. 
*               The same event could be received using the ReceiveEvt API.    
* Date:         24/07/16
************************************************************************/
EventStatusType GenerateEvt (EventStructureType *Event)
{
   /* Event Status */
   EventStatusType EventStatus = EventIdle;

   /* Send the event */
   Event->EventStatus = EventSent;
   /* Update event status */
   EventStatus = EventSent;

   /* Return event status */
   return(EventStatus);
}
	
/************************************************************************
* Function:     void ReceiveEvt (EventStructureType *Event)
* Input:        EventStructureType *Event
* Output:       EventStatusType
* Author:       F.Ficili	
* Description:  API to receive an event. 
*               The API takes an event variable passed by reference as an input. 
*               The event had to be previously generated by a GenerateEvt API.  
* Date:         24/07/16
************************************************************************/
EventStatusType ReceiveEvt (EventStructureType *Event)
{
   /* Event Status */
   EventStatusType EventStatus = EventIdle;

   /* Check event status */
   if (Event->EventStatus == EventSent)
   {
      /* The event is now received */
      Event->EventStatus = EventReceived;
      /* Update event status */
      EventStatus = EventReceived;
   }
   else
   {
      /* Update event status */
      EventStatus = EventIdle;
   }
   
   /* Return event status */
   return(EventStatus);
}
